name: Release Binaries

on:
  workflow_dispatch:
    inputs:
      go2rtc_version:
        description: Specify go2rtc version
        required: true
        default: v1.9.2

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Binaries
        run: bash ./build/build.sh ${{ github.event.inputs.go2rtc_version }}

      - name: Compress Binaries
        run: |
          set -e
          set -o pipefail
          cat bin/go2rtc_linux_amd64 | gzip --best >bin/go2rtc_linux_amd64.gz
          cat bin/go2rtc_linux_arm64 | gzip --best >bin/go2rtc_linux_arm64.gz
          cat bin/go2rtc_linux_arm | gzip --best >bin/go2rtc_linux_arm.gz
          cat bin/go2rtc_linux_i386 | gzip --best >bin/go2rtc_linux_i386.gz
          cat bin/go2rtc_linux_mipsel | gzip --best >bin/go2rtc_linux_mipsel.gz
          cat bin/go2rtc_mac_amd64 | gzip --best >bin/go2rtc_mac_amd64.gz
          cat bin/go2rtc_mac_arm64 | gzip --best >bin/go2rtc_mac_arm64.gz
          cat bin/go2rtc_win_amd64.exe | gzip --best >bin/go2rtc_win_amd64.exe.gz
          cat bin/go2rtc_win_arm64.exe | gzip --best >bin/go2rtc_win_arm64.exe.gz
          cat bin/go2rtc_win_i386.exe | gzip --best >bin/go2rtc_win_i386.exe.gz
          ls -l bin
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: bin-${{ github.event.inputs.go2rtc_version }}
          name: go2rtc ${{ github.event.inputs.go2rtc_version }} binaries
          body: For changelog look [here](https://github.com/AlexxIT/go2rtc/releases/tag/${{ github.event.inputs.go2rtc_version }}).
          files: |
            bin/go2rtc_linux_amd64.gz
            bin/go2rtc_linux_amd64.LICENSE
            bin/go2rtc_linux_arm64.gz
            bin/go2rtc_linux_arm64.LICENSE
            bin/go2rtc_linux_arm.gz
            bin/go2rtc_linux_arm.LICENSE
            bin/go2rtc_linux_i386.gz
            bin/go2rtc_linux_i386.LICENSE
            bin/go2rtc_linux_mipsel.gz
            bin/go2rtc_linux_mipsel.LICENSE
            bin/go2rtc_mac_amd64.gz
            bin/go2rtc_mac_amd64.LICENSE
            bin/go2rtc_mac_arm64.gz
            bin/go2rtc_mac_arm64.LICENSE
            bin/go2rtc_win_amd64.exe.gz
            bin/go2rtc_win_amd64.LICENSE
            bin/go2rtc_win_arm64.exe.gz
            bin/go2rtc_win_arm64.LICENSE
            bin/go2rtc_win_i386.exe.gz
            bin/go2rtc_win_i386.LICENSE
